# Introduction

According to David Harvey, modernism ended at 3 pm, on March 16, 1972, when demolition of the Pruitt-Igoe housing project in St. Louis, Missouri began [@HarveyConditionPostmodernityEnquiry1991].
This was also roughly the same time the Fordist regime of accumulation, which had been dominant in the West, was coming to an end. In academic economics, the University of Chicago's Robert Lucas, Jr. was about launch a conservative assault against Keynesian theory, while in Chile Augsto Pinochet led an actual assault on La Moneda and overthrew Chile's democratially elected president, Salvadore Allende. Within a few years Pinochet's government, advised by a group of economists called the "Chicago Boys" because they had learned their ideas at the University of Chicago, would completely overhall the Chilean economy.
In the core of the global economy, Margaret Thatcher and Ronald Reagan would soon follow Pinochet,and proceed to dismantle their respective Keynesian welfare states.This process continued through the 1990s.
Postmodernism also gained ascendancy in academia, in the wider culture, and in human settlements.

TODO: CITE SOURCES
commenced, and neoliberalism began its assent to hegemony over the capitalist world, which in due time would be practically the entire world itself.

Readers might be wondering what does all this have to do with the 2020 COVID crisis? Well consider this. In the 1950's the USA and USSR led a global effort to eradicate smallpox.
TODO: GET CITATIONS AND LEARN MORE ABOUT THIS
In the midst of the Cold War, the two superpowers ascribed to seemingly opposing ideologies. But beneath this veneer, both indeologies extolled progress, truth, science.^[This is not to say the two were above superstition or spreading false propaganda. TODO: MAYBE ADD MORE HERE.]
This presented enough common ground for the two to join together to lead (or at least compete for the leadership of) the United Nations in global effort to erradicate smallpox.
